<a href="https://colab.research.google.com/github/anshulkr69/learning-to-make-machine-learn/blob/main/6_handling_categorical_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Types of Categorical Data:
1. Nominal (can't be ranked i.e. there is no particular priority order of data eg. Branches in a clg, States in a Country...)

2. Ordinal (can be ranked eg. grades)




### The problem with categorical data is that they are not number but objects, and handling objects is way more difficult than numbers because finding correlation b/w objects and studying it using statistics is tricky or even impossible. So we need encoding and therefore we will be studying different types of encoding:

## IMPORTS

In [1]:
import pandas as pd
import numpy as np

# 1. Ordinal Encoding
  -Used on ordinal categorical data
# 2. Label Encoding
-Used on ordinal categorical data

*PS: dono same hi hain, the only difference is that first is used for the input data whereas the later is used for labels/Y/output data
Just different libraries in scikit for different purpose doing same thing.*

In [2]:
df = pd.read_csv("/content/drive/MyDrive/Datasets/customer.csv")

In [3]:
df.shape

(50, 5)

In [5]:
df.sample(5)

    age  gender review education purchased
26   53  Female   Poor        PG        No
17   22  Female   Poor        UG       Yes
12   51    Male   Poor    School        No
11   74    Male   Good        UG       Yes
49   25  Female   Good        UG        No

In [6]:
df = df.iloc[:,2:]
df

     review education purchased
0   Average    School        No
1      Poor        UG        No
2      Good        PG        No
3      Good        PG        No
4   Average        UG        No
5   Average    School       Yes
6      Good    School        No
7      Poor    School       Yes
8   Average        UG        No
9      Good        UG       Yes
10     Good        UG       Yes
11     Good        UG       Yes
12     Poor    School        No
13  Average    School        No
14     Poor        PG       Yes
15     Poor        UG        No
16     Poor        UG       Yes
17     Poor        UG       Yes
18     Good    School        No
19     Poor        PG       Yes
20  Average    School       Yes
21  Average        PG        No
22     Poor        PG       Yes
23     Good    School        No
24  Average        PG       Yes
25     Good    School        No
26     Poor        PG        No
27     Poor        PG        No
28     Poor    School        No
29  Average        UG       Yes
30  Average        UG        No
31     Poor    School       Yes
32  Average        UG       Yes
33     Good        PG       Yes
34  Average    School        No
35     Poor    School       Yes
36     Good        UG       Yes
37  Average        PG       Yes
38     Good    School        No
39     Poor        PG        No
40     Good    School        No
41     Good        PG       Yes
42     Good        PG       Yes
43     Poor        PG        No
44  Average        UG        No
45     Poor        PG       Yes
46     Poor        PG        No
47     Good        PG       Yes
48     Good        UG       Yes
49     Good        UG        No

In [17]:
df['education'].unique()

array(['School', 'UG', 'PG'], dtype=object)

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.drop('purchased',axis=1),df['purchased'],
test_size= 0.2)
x_train.shape,x_test.shape

((40, 2), (10, 2))

In [18]:
from sklearn.preprocessing import OrdinalEncoder
oe= OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [19]:
oe.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [20]:
x_train=oe.transform(x_train)
x_test=oe.transform(x_test)

In [21]:
x_train

array([[2., 1.],
       [2., 1.],
       [1., 1.],
       [0., 2.],
       [2., 1.],
       [2., 1.],
       [0., 1.],
       [1., 0.],
       [2., 0.],
       [1., 0.],
       [0., 2.],
       [2., 2.],
       [0., 2.],
       [2., 1.],
       [0., 0.],
       [2., 0.],
       [1., 0.],
       [2., 2.],
       [2., 2.],
       [0., 2.],
       [2., 2.],
       [0., 0.],
       [2., 0.],
       [0., 1.],
       [1., 1.],
       [0., 0.],
       [2., 0.],
       [2., 0.],
       [1., 2.],
       [0., 2.],
       [0., 1.],
       [1., 1.],
       [0., 1.],
       [2., 2.],
       [0., 2.],
       [0., 2.],
       [0., 2.],
       [1., 0.],
       [1., 1.],
       [1., 2.]])

In [30]:
# we dont actually need to change the array into a DF, the scikit learn functions natively
# do that. Basically they can accept both array and DF/Series

x_train=pd.DataFrame(x_train,columns=df.iloc[:,0:2].columns)
x_test=pd.DataFrame(x_test,columns=df.iloc[:,0:2].columns)

In [32]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

# WE DON'T PASS CATEGORIES IN LABEL ENCODING!!!

In [26]:
le.fit(y_train)

LabelEncoder()

In [29]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [31]:
y_train=le.transform(y_train)
y_test=le.transform(y_test)